:PROPERTIES:
:ID:       03ff4dce-f21e-4b99-8ada-dee0415142c3

:END:
#+title: proyecto-derivative-calculator
#+category: PROJECT
#+filetags: python

* Objective
Build a derivative calculator. 

* Rough Plan

** Make the program Able to perform algebraic Reduction (Computational Algebra)
- The superficial plan is to use a dictionary. The keys are the grades and the value are the coeficients. This is great to sum the terms that are the same grade, but it doesn't help with something like "2ex + 3x" ya que no será fácil hacer la suma de "2e" y "3". Moreover, this approach only works with expressions that only have one variable.

*** Literature

** Computational differentiation
* Investigation

* Ideas

** TODO Make the program able to perform algebraic reduction
- Use a dictionary to save

** TODO Derivate [In progress]
I will have to use some algorithm to implement the differentition. Here I will list some literature in the topic. The kind of differentiation that I want to perform is computational symbolic differentiation.
- https://sci-hub.se/https://doi.org/10.1145/1275808.1276512
- https://sci-hub.se/https://doi.org/10.1016/S0098-1354(97)00264-0
