:PROPERTIES:
:ID:       23c375cb-fd20-4a6c-adbc-73b5bb643877
:END:
#+title: Journal - RTrading - 01222025
#+category: JOURNAL
#+filetags: :journal:trading:

* Análisis
** BTC
We an get a SHORT in 4h if the price enter the range and pullback to the top of the range.
** DOGE
*** Pre
DOGE looks like is in the middle of nowhere, I will have to wait for it to reach a node of return to the POC.
- *Price:* 0.36595
- *POC:* 0.38899
- *HVN*: 0.36467 ~ 0.35987 
- *Tendency*: Ranging (0.44245 ~ 0.33805)
- *Looking for:* LONG from HVN
  /No divergencies so far/
** XRP
*** Pre
XRP it's near a resistance level located by the volume profile (a VAH). I can consider a *short* when it reach the resistance zone.
- *Price:* 3.2500
- *HVN1*: 3.2483 ~ 3.2890 
- *HVN2*: 3.0823 ~ 3.1355
- *POC:* Too far away
- *Tendency:* Bullish
- *Looking for:* LONG from HVN2
  /No divergencies so far/
** SOL
*** Pre
It is near the VAH there could be a short but it would be better to wait till it lose the HVN below the price to make a short
- *Price:* 260
- *HVN*: 256.49 ~ 252.69
- *POC:* Too far away
- *Tendency:* Ranging (260.04 ~ 168.42)
- *Looking for:* SHORT
  /No divergencies so far/
*** During
There was a trade but I didn't take because I didn't see it :c. It went to profit
